import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import { randomUUID } from 'crypto';

const DEFAULT_MODEL = '@cf/black-forest-labs/flux-1-schnell';

export type CloudflareImageInput = {
  prompt: string;
  aspect: '1:1' | '9:16';
  brand?: string;
  headline?: string;
};

function cloudflareConfig(): { token: string; accountId: string } | null {
  const token = process.env.CLOUDFLARE_API_TOKEN;
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
  if (!token || !accountId) return null;
  return { token, accountId };
}

function modelId(): string {
  return process.env.CLOUDFLARE_IMAGE_MODEL || DEFAULT_MODEL;
}

/** Save generated bytes under public/uploads/cloudflare */
export async function saveCloudflareAsset(bytes: Buffer): Promise<string> {
  const dir = path.join(process.cwd(), 'public', 'uploads', 'cloudflare');
  await mkdir(dir, { recursive: true });
  const filename = `${Date.now()}-${randomUUID().slice(0, 8)}.png`;
  await writeFile(path.join(dir, filename), bytes);
  return `/uploads/cloudflare/${filename}`;
}

/**
 * Generate ad scene via Cloudflare Workers AI (FLUX Schnell).
 * Free tier: 10,000 Neurons/day (~200+ images).
 */
export async function generateCloudflareImage(
  input: CloudflareImageInput
): Promise<{ url: string } | null> {
  const cfg = cloudflareConfig();
  if (!cfg) return null;

  const aspectHint =
    input.aspect === '9:16'
      ? 'Vertical 9:16 portrait composition for Instagram Stories/Reels.'
      : 'Square 1:1 composition for Meta Feed.';

  const prompt = [
    input.prompt,
    aspectHint,
    input.brand ? `Brand: ${input.brand}.` : '',
    input.headline ? `Ad theme: ${input.headline}.` : '',
    'Photorealistic Indian D2C food product advertising photography.',
    'Professional studio lighting, appetizing, no watermark, no text overlay.',
  ]
    .filter(Boolean)
    .join(' ')
    .slice(0, 2048);

  const model = modelId();
  const url = `https://api.cloudflare.com/client/v4/accounts/${cfg.accountId}/ai/run/${model}`;

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${cfg.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt,
        steps: 4,
      }),
      signal: AbortSignal.timeout(120000),
    });

    const contentType = res.headers.get('content-type') || '';

    if (contentType.includes('application/json')) {
      const json = (await res.json()) as {
        success?: boolean;
        errors?: Array<{ message?: string }>;
        result?: { image?: string };
      };
      if (!res.ok || json.success === false) {
        console.warn('[cloudflare-image]', json.errors?.[0]?.message || json);
        return null;
      }
      const b64 = json.result?.image;
      if (!b64) return null;
      const saved = await saveCloudflareAsset(Buffer.from(b64, 'base64'));
      return { url: saved };
    }

    if (!res.ok) {
      console.warn('[cloudflare-image] HTTP', res.status);
      return null;
    }

    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length === 0) return null;
    const saved = await saveCloudflareAsset(buf);
    return { url: saved };
  } catch (err) {
    console.warn('[cloudflare-image]', err instanceof Error ? err.message : err);
    return null;
  }
}
