import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import { randomUUID } from 'crypto';

const API_BASE = 'https://generativelanguage.googleapis.com/v1beta';

function geminiKey(): string | null {
  return process.env.GEMINI_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY || null;
}

function imageModel(): string {
  return process.env.GEMINI_IMAGE_MODEL || 'gemini-2.5-flash-image';
}

function videoModel(): string {
  return process.env.GEMINI_VIDEO_MODEL || 'veo-3.1-fast-generate-preview';
}

async function fetchProductBase64(url: string): Promise<{ data: string; mimeType: string } | null> {
  try {
    const res = await fetch(url, {
      signal: AbortSignal.timeout(15000),
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36',
        Accept: 'image/*',
      },
    });
    if (!res.ok) return null;
    const mimeType = res.headers.get('content-type')?.split(';')[0] || 'image/jpeg';
    if (!mimeType.startsWith('image/')) return null;
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length === 0 || buf.length > 4_000_000) return null;
    return { data: buf.toString('base64'), mimeType };
  } catch {
    return null;
  }
}

function extractImageFromResponse(json: Record<string, unknown>): string | null {
  const candidates = json.candidates as Array<Record<string, unknown>> | undefined;
  const parts = (candidates?.[0]?.content as Record<string, unknown>)?.parts as
    | Array<Record<string, unknown>>
    | undefined;
  if (!parts) return null;
  for (const part of parts) {
    const inline = part.inlineData as { data?: string; mimeType?: string } | undefined;
    if (inline?.data) return inline.data;
  }
  return null;
}

/** Save generated bytes under public/uploads/gemini for browser + Meta access */
export async function saveGeminiAsset(
  bytes: Buffer,
  ext: 'png' | 'mp4' = 'png'
): Promise<string> {
  const dir = path.join(process.cwd(), 'public', 'uploads', 'gemini');
  await mkdir(dir, { recursive: true });
  const filename = `${Date.now()}-${randomUUID().slice(0, 8)}.${ext}`;
  await writeFile(path.join(dir, filename), bytes);
  return `/uploads/gemini/${filename}`;
}

export type GeminiImageInput = {
  prompt: string;
  aspect: '1:1' | '9:16';
  productImageUrl?: string | null;
  brand?: string;
  headline?: string;
};

/**
 * Generate ad scene/creative via Gemini native image (Nano Banana).
 * Uses product reference image when available.
 */
export async function generateGeminiImage(
  input: GeminiImageInput
): Promise<{ url: string } | null> {
  const key = geminiKey();
  if (!key) return null;

  const aspectHint =
    input.aspect === '9:16'
      ? 'Vertical 9:16 Meta Stories/Reels format. Leave lower third clear for text overlay.'
      : 'Square 1:1 Meta Feed format.';

  const fullPrompt = [
    input.prompt,
    aspectHint,
    input.brand ? `Brand: ${input.brand}.` : '',
    input.headline ? `Ad headline theme: "${input.headline}".` : '',
    'Photorealistic Indian D2C ecommerce ad photography. No watermark. No misspelled text.',
  ]
    .filter(Boolean)
    .join(' ');

  const parts: Array<Record<string, unknown>> = [{ text: fullPrompt }];

  if (input.productImageUrl) {
    const product = await fetchProductBase64(input.productImageUrl);
    if (product) {
      parts.push({
        text: 'Use this exact product packaging in the scene — keep label, colors, and jar shape accurate.',
      });
      parts.push({ inlineData: { mimeType: product.mimeType, data: product.data } });
    }
  }

  try {
    const model = imageModel();
    const res = await fetch(
      `${API_BASE}/models/${model}:generateContent?key=${encodeURIComponent(key)}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts }],
          generationConfig: {
            responseModalities: ['IMAGE'],
          },
        }),
        signal: AbortSignal.timeout(120000),
      }
    );

    const json = (await res.json()) as Record<string, unknown>;
    if (!res.ok) {
      console.warn('[gemini-image]', json);
      return null;
    }

    const b64 = extractImageFromResponse(json);
    if (!b64) {
      return generateImagenFallback(fullPrompt, input.aspect);
    }

    const url = await saveGeminiAsset(Buffer.from(b64, 'base64'), 'png');
    return { url };
  } catch (err) {
    console.warn('[gemini-image]', err instanceof Error ? err.message : err);
    return generateImagenFallback(
      [
        input.prompt,
        input.brand ? `Brand: ${input.brand}.` : '',
      ]
        .filter(Boolean)
        .join(' '),
      input.aspect
    );
  }
}

async function generateImagenFallback(
  prompt: string,
  aspect: '1:1' | '9:16'
): Promise<{ url: string } | null> {
  const key = geminiKey();
  if (!key) return null;

  try {
    const res = await fetch(
      `${API_BASE}/models/imagen-4.0-generate-001:predict?key=${encodeURIComponent(key)}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          instances: [{ prompt: prompt.slice(0, 480) }],
          parameters: {
            sampleCount: 1,
            aspectRatio: aspect === '9:16' ? '9:16' : '1:1',
          },
        }),
        signal: AbortSignal.timeout(120000),
      }
    );
    const json = (await res.json()) as Record<string, unknown>;
    if (!res.ok) {
      console.warn('[imagen]', json);
      return null;
    }
    const predictions = json.predictions as Array<{ bytesBase64Encoded?: string }> | undefined;
    const b64 = predictions?.[0]?.bytesBase64Encoded;
    if (!b64) return null;
    const url = await saveGeminiAsset(Buffer.from(b64, 'base64'), 'png');
    return { url };
  } catch (err) {
    console.warn('[imagen]', err instanceof Error ? err.message : err);
    return null;
  }
}

export type GeminiVideoInput = {
  prompt: string;
  aspect: '1:1' | '9:16';
  referenceImageUrl?: string | null;
  durationSeconds?: number;
};

/**
 * Generate short product video via Veo (paid tier). Polls until ready or timeout.
 */
export async function generateGeminiVideo(
  input: GeminiVideoInput
): Promise<{ url: string } | null> {
  const key = geminiKey();
  if (!key) return null;

  const duration = Math.min(8, Math.max(4, input.durationSeconds || 6));
  const aspectRatio = input.aspect === '9:16' ? '9:16' : '1:1';

  const prompt = [
    input.prompt,
    `${duration} second cinematic product ad clip for Meta Reels.`,
    'Smooth camera motion, appetizing food lighting, professional D2C commercial.',
  ].join(' ');

  try {
    const model = videoModel();
    const startRes = await fetch(
      `${API_BASE}/models/${model}:predictLongRunning?key=${encodeURIComponent(key)}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          instances: [{ prompt }],
          parameters: {
            aspectRatio,
            durationSeconds: duration,
            sampleCount: 1,
          },
        }),
        signal: AbortSignal.timeout(30000),
      }
    );

    const startJson = (await startRes.json()) as Record<string, unknown>;
    if (!startRes.ok) {
      console.warn('[gemini-video] start', startJson);
      return null;
    }

    const operationName = startJson.name as string | undefined;
    if (!operationName) return null;

    const deadline = Date.now() + 180000;
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 8000));
      const pollRes = await fetch(
        `${API_BASE}/${operationName}?key=${encodeURIComponent(key)}`,
        { signal: AbortSignal.timeout(30000) }
      );
      const pollJson = (await pollRes.json()) as Record<string, unknown>;
      if (!pollRes.ok) {
        console.warn('[gemini-video] poll', pollJson);
        return null;
      }
      if (pollJson.done) {
        const response = pollJson.response as Record<string, unknown> | undefined;
        const samples = (response?.generateVideoResponse as Record<string, unknown>)
          ?.generatedSamples as Array<Record<string, unknown>> | undefined;
        const videoUri = (samples?.[0]?.video as { uri?: string })?.uri;
        if (videoUri) {
          const vidRes = await fetch(videoUri, {
            headers: { 'x-goog-api-key': key },
            signal: AbortSignal.timeout(120000),
          });
          if (!vidRes.ok) return null;
          const url = await saveGeminiAsset(
            Buffer.from(await vidRes.arrayBuffer()),
            'mp4'
          );
          return { url };
        }
        return null;
      }
    }
    console.warn('[gemini-video] timeout');
    return null;
  } catch (err) {
    console.warn('[gemini-video]', err instanceof Error ? err.message : err);
    return null;
  }
}
