import type { OptimizeAccountInput } from './types';

/** Sample account for Optimize Hub before Meta is connected. */
export function dryRunOptimizeAccount(): OptimizeAccountInput {
  return {
    brandName: 'Demo Pickles Co',
    websiteUrl: 'https://example.com',
    targets: {
      cpaTarget: 100,
      roasTarget: 2.5,
      dailyBudgetCap: 5000,
      aov: 499,
      marginPct: 40,
      ltv: 1400,
    },
    tracking: {
      pixelConnected: true,
      pixelId: '1234567890',
      capiEnabled: false,
      emqScore: 6.2,
      dedupRate: 0.55,
      domainVerified: false,
      eventsSeen: ['ViewContent', 'AddToCart'],
      purchaseEvents7d: 0,
    },
    priorDaysCpa: {
      'dry-camp-2': [190, 205, 188],
    },
    campaigns: [
      {
        id: 'dry-camp-1',
        name: 'Festive Pickles · Traffic',
        status: 'active',
        objective: 'OUTCOME_TRAFFIC',
        budgetType: 'ABO',
        biddingStrategy: 'LOWEST_COST',
        dailyBudget: 500,
        spend: 428,
        impressions: 18420,
        clicks: 312,
        cpc: 1.37,
        cpm: 23.2,
        ctr: 1.69,
        cpa: 86,
        roas: 2.4,
        frequency: 2.1,
        purchases: 5,
        addToCart: 28,
        initiateCheckout: 11,
        conversionRate: 1.6,
        revenue: 1028,
        reach: 8760,
        hasExclusions: true,
        hasLookalike: false,
        attributionWindow: '7d_click_1d_view',
      },
      {
        id: 'dry-camp-2',
        name: 'UGC Stories · Conversions',
        status: 'active',
        objective: 'OUTCOME_SALES',
        budgetType: 'CBO',
        biddingStrategy: 'COST_CAP',
        dailyBudget: 800,
        spend: 760,
        impressions: 42100,
        clicks: 210,
        cpc: 3.62,
        cpm: 18.1,
        ctr: 0.5,
        cpa: 190,
        roas: 0.9,
        frequency: 4.2,
        purchases: 4,
        addToCart: 14,
        initiateCheckout: 6,
        conversionRate: 1.9,
        revenue: 684,
        reach: 10020,
        learningLimited: true,
        hasExclusions: false,
        hasLookalike: false,
        attributionWindow: '7d_click_1d_view',
      },
    ],
    creatives: [
      {
        id: 'cr-1',
        name: 'Offer bundle',
        format: 'carousel',
        headline: '8 jars for ₹599',
        primaryText: 'Family variety pack — free shipping',
        spend: 200,
        ctr: 1.8,
        cpa: 80,
        frequency: 2.0,
        conceptCluster: 'bundle_value',
      },
      {
        id: 'cr-2',
        name: 'Offer bundle v2',
        format: 'carousel',
        headline: '8 jars for ₹599',
        primaryText: 'Family variety pack — free shipping today',
        spend: 180,
        ctr: 1.5,
        cpa: 90,
        frequency: 2.4,
        conceptCluster: 'bundle_value',
      },
      {
        id: 'cr-3',
        name: 'UGC kitchen',
        format: 'video',
        headline: 'Mom-approved crunch',
        primaryText: 'Real kitchen taste test',
        spend: 220,
        ctr: 0.7,
        cpa: 150,
        frequency: 3.8,
        conceptCluster: 'ugc_social_proof',
      },
      {
        id: 'cr-4',
        name: 'Stories packshot',
        format: 'stories',
        headline: 'Shop the jar',
        primaryText: 'Limited festive stock',
        spend: 160,
        ctr: 1.1,
        cpa: 110,
        frequency: 2.9,
        conceptCluster: 'packshot_offer',
      },
    ],
  };
}
